services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginx:latest
    container_name: ct-task-nginx
    volumes:
      - ./public:/var/www/public
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_started

  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: ct-task-php
    volumes:
      - ./:/var/www
    depends_on:
      mysql:
        condition: service_healthy

  pg:
    restart: unless-stopped
    image: postgres:15.14-alpine
    container_name: ct-task-postgres
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'ct-task-pg_local:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: ct-task-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_DATABASES: 1
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_PORT: '${REDIS_PORT:-6379}'

  vite:
    build:
      context: .
      dockerfile: ./docker/vite/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    container_name: ct-task-vite
    restart: unless-stopped
    environment:
      VITE_APP_NAME: '${VITE_APP_NAME}'
      VITE_APP_URL: '${VITE_APP_URL}'

volumes:
  ct-task-pg_local:
    driver: local
